/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jesus.view.login;

import com.jesus.view.register.*;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.jesus.view.admindashboard.AdminDashboardForm;
import com.jesus.view.components.PieChart;
import java.awt.Button;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Juan `Aether` Martínez <jotamartinezd at gmail.com>
 */
public class LoginForm extends javax.swing.JFrame {

	/**
	 * Creates new form RegisterFrae
	 */
	public LoginForm() {
		initComponents();

		UIManager.put( "Button.arc", 20);
		UIManager.put("TextComponent.arc", 10);
		UIManager.put("Label.arc", 10);
		UIManager.put( "Component.innerFocusWidth", 1 );
		UIManager.put("Component.focusWidth", 1);
		UIManager.put("Component.borderColor", new Color(71, 97, 75));
		UIManager.put("Component.selectionBackground", new Color(71, 97, 75));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jpnMainPane = new javax.swing.JPanel();
    jpnWelcomePane = new javax.swing.JPanel();
    panelCover2 = new com.jesus.view.components.PanelCover();
    lblWelcomeBack = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    btnRegisterNewUser = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jpnLoginPane = new javax.swing.JPanel();
    lblEmail = new javax.swing.JLabel();
    lblPassword = new javax.swing.JLabel();
    btnLogin = new javax.swing.JButton();
    txtEmail = new javax.swing.JTextField();
    lblLogin = new javax.swing.JLabel();
    txtPassword = new javax.swing.JPasswordField();
    btnForgotPassword = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jpnMainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jpnWelcomePane.setBackground(new java.awt.Color(51, 204, 0));

    lblWelcomeBack.setFont(new java.awt.Font("Carlito", 0, 36)); // NOI18N
    lblWelcomeBack.setForeground(new java.awt.Color(255, 255, 255));
    lblWelcomeBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblWelcomeBack.setText("Welcome back!");

    jLabel1.setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText(" Welcome back to the Vehicle Counting Assistant");
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    btnRegisterNewUser.setBackground(new java.awt.Color(0, 100, 54));
    btnRegisterNewUser.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
    btnRegisterNewUser.setForeground(new java.awt.Color(255, 255, 255));
    btnRegisterNewUser.setText("Register new user");
    btnRegisterNewUser.setBorderPainted(false);
    btnRegisterNewUser.setContentAreaFilled(false);
    btnRegisterNewUser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegisterNewUserActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Login and start monitoring the retrieved data");

    javax.swing.GroupLayout panelCover2Layout = new javax.swing.GroupLayout(panelCover2);
    panelCover2.setLayout(panelCover2Layout);
    panelCover2Layout.setHorizontalGroup(
      panelCover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lblWelcomeBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(panelCover2Layout.createSequentialGroup()
        .addGroup(panelCover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(panelCover2Layout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addComponent(btnRegisterNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13))
          .addGroup(panelCover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCover2Layout.createSequentialGroup()
              .addGap(6, 6, 6)
              .addComponent(jLabel3))
            .addComponent(jLabel1)))
        .addContainerGap(30, Short.MAX_VALUE))
    );
    panelCover2Layout.setVerticalGroup(
      panelCover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCover2Layout.createSequentialGroup()
        .addGap(154, 154, 154)
        .addComponent(lblWelcomeBack)
        .addGap(45, 45, 45)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
        .addComponent(btnRegisterNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(107, 107, 107))
    );

    javax.swing.GroupLayout jpnWelcomePaneLayout = new javax.swing.GroupLayout(jpnWelcomePane);
    jpnWelcomePane.setLayout(jpnWelcomePaneLayout);
    jpnWelcomePaneLayout.setHorizontalGroup(
      jpnWelcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelCover2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jpnWelcomePaneLayout.setVerticalGroup(
      jpnWelcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelCover2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jpnMainPane.add(jpnWelcomePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 530));

    jpnLoginPane.setBackground(new java.awt.Color(255, 255, 255));
    jpnLoginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblEmail.setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
    lblEmail.setForeground(new java.awt.Color(0, 0, 0));
    lblEmail.setText("Email");
    jpnLoginPane.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

    lblPassword.setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
    lblPassword.setForeground(new java.awt.Color(0, 0, 0));
    lblPassword.setText("Password");
    jpnLoginPane.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

    btnLogin.setBackground(new java.awt.Color(255, 255, 255));
    btnLogin.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
    btnLogin.setForeground(new java.awt.Color(0, 0, 0));
    btnLogin.setText("Login");
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });
    jpnLoginPane.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 170, 40));

    txtEmail.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
    jpnLoginPane.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, 40));

    lblLogin.setFont(new java.awt.Font("Carlito", 1, 36)); // NOI18N
    lblLogin.setForeground(new java.awt.Color(16, 170, 74));
    lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblLogin.setText("Login");
    jpnLoginPane.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 704, -1));

    txtPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtPasswordActionPerformed(evt);
      }
    });
    jpnLoginPane.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 250, 40));

    btnForgotPassword.setBackground(new java.awt.Color(255, 255, 255));
    btnForgotPassword.setForeground(new java.awt.Color(139, 79, 90));
    btnForgotPassword.setText("I forgot my password");
    btnForgotPassword.setBorderPainted(false);
    btnForgotPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnForgotPasswordActionPerformed(evt);
      }
    });
    jpnLoginPane.add(btnForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

    jpnMainPane.add(jpnLoginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 710, 530));

    getContentPane().add(jpnMainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 530));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtPasswordActionPerformed

  private void btnRegisterNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterNewUserActionPerformed
    // TODO add your handling code here:
		RegisterForm registerFrame = new RegisterForm();
		this.setVisible(false);
		registerFrame.setVisible(true);
  }//GEN-LAST:event_btnRegisterNewUserActionPerformed

  private void btnForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPasswordActionPerformed
    // TODO add your handling code here:
		JOptionPane.showMessageDialog(null, "This functionality is yet to be done", "YET TO DO", 0);
  }//GEN-LAST:event_btnForgotPasswordActionPerformed

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    // TODO add your handling code here:

		AdminDashboardForm adminDashboardForm = new AdminDashboardForm();

		this.setVisible(false);
		adminDashboardForm.setVisible(true);
  }//GEN-LAST:event_btnLoginActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnForgotPassword;
  private javax.swing.JButton btnLogin;
  private javax.swing.JButton btnRegisterNewUser;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jpnLoginPane;
  private javax.swing.JPanel jpnMainPane;
  private javax.swing.JPanel jpnWelcomePane;
  private javax.swing.JLabel lblEmail;
  private javax.swing.JLabel lblLogin;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblWelcomeBack;
  private com.jesus.view.components.PanelCover panelCover2;
  private javax.swing.JTextField txtEmail;
  private javax.swing.JPasswordField txtPassword;
  // End of variables declaration//GEN-END:variables
}
