/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jesus.view.userapp;

/**
 *
 * @author Juan `Aether` Martínez <jotamartinezd at gmail.com>
 */
public class UserAppForm extends javax.swing.JFrame {

	/**
	 * Creates new form UserAppForm
	 */
	public UserAppForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    lblMovement = new javax.swing.JLabel();
    btnMenu = new javax.swing.JButton();
    btnStatisticsSection = new javax.swing.JButton();
    btnAddCount = new javax.swing.JButton();
    btnCountingSection = new javax.swing.JButton();
    btnCountedSection = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    lblVehicle = new javax.swing.JLabel();
    btnAdd = new javax.swing.JButton();
    btnSubstract = new javax.swing.JButton();
    txtQuantity = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtQuantity2 = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    txtQuantity3 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    txtQuantity4 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txtQuantity5 = new javax.swing.JTextField();
    btnAdd2 = new javax.swing.JButton();
    btnSubstract2 = new javax.swing.JButton();
    btnSubstract3 = new javax.swing.JButton();
    btnAdd3 = new javax.swing.JButton();
    btnSubstract4 = new javax.swing.JButton();
    btnAdd4 = new javax.swing.JButton();
    btnSubstract5 = new javax.swing.JButton();
    btnAdd5 = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    btnNewVehicle = new javax.swing.JButton();
    btnFinishCount = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel2.setBackground(new java.awt.Color(20, 175, 113));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblMovement.setFont(new java.awt.Font("Carlito", 0, 36)); // NOI18N
    lblMovement.setForeground(new java.awt.Color(255, 255, 255));
    lblMovement.setText("NS - 1");
    jPanel2.add(lblMovement, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, -1));

    btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/list.png"))); // NOI18N
    btnMenu.setBorderPainted(false);
    btnMenu.setContentAreaFilled(false);
    jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

    btnStatisticsSection.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
    btnStatisticsSection.setForeground(new java.awt.Color(255, 255, 255));
    btnStatisticsSection.setText("Statistics");
    btnStatisticsSection.setBorderPainted(false);
    btnStatisticsSection.setContentAreaFilled(false);
    jPanel2.add(btnStatisticsSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 63, 120, 30));

    btnAddCount.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
    btnAddCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/add.png"))); // NOI18N
    btnAddCount.setBorderPainted(false);
    btnAddCount.setContentAreaFilled(false);
    btnAddCount.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddCountActionPerformed(evt);
      }
    });
    jPanel2.add(btnAddCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 40));

    btnCountingSection.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
    btnCountingSection.setForeground(new java.awt.Color(255, 255, 255));
    btnCountingSection.setText("Counting");
    btnCountingSection.setBorderPainted(false);
    btnCountingSection.setContentAreaFilled(false);
    jPanel2.add(btnCountingSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, 110, 30));

    btnCountedSection.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
    btnCountedSection.setForeground(new java.awt.Color(255, 255, 255));
    btnCountedSection.setText("Counted");
    btnCountedSection.setBorderPainted(false);
    btnCountedSection.setContentAreaFilled(false);
    jPanel2.add(btnCountedSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 63, 100, 30));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 100));

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/car(1).png"))); // NOI18N
    jPanel3.add(lblVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 90));

    btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/add(1).png"))); // NOI18N
    btnAdd.setBorderPainted(false);
    btnAdd.setContentAreaFilled(false);
    jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 40, 50));

    btnSubstract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/remove.png"))); // NOI18N
    btnSubstract.setBorderPainted(false);
    btnSubstract.setContentAreaFilled(false);
    jPanel3.add(btnSubstract, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, 50));

    txtQuantity.setFocusable(false);
    txtQuantity.setRequestFocusEnabled(false);
    jPanel3.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 100, 30));

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/car(1).png"))); // NOI18N
    jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 90));

    txtQuantity2.setFocusable(false);
    txtQuantity2.setRequestFocusEnabled(false);
    jPanel3.add(txtQuantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 100, 30));

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/car(1).png"))); // NOI18N
    jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 90));

    txtQuantity3.setFocusable(false);
    txtQuantity3.setRequestFocusEnabled(false);
    jPanel3.add(txtQuantity3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 100, 30));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/car(1).png"))); // NOI18N
    jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 90));

    txtQuantity4.setFocusable(false);
    txtQuantity4.setRequestFocusEnabled(false);
    jPanel3.add(txtQuantity4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 100, 30));

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/car(1).png"))); // NOI18N
    jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 90));

    txtQuantity5.setFocusable(false);
    txtQuantity5.setRequestFocusEnabled(false);
    jPanel3.add(txtQuantity5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 100, 30));

    btnAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/add(1).png"))); // NOI18N
    btnAdd2.setBorderPainted(false);
    btnAdd2.setContentAreaFilled(false);
    jPanel3.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 40, 50));

    btnSubstract2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/remove.png"))); // NOI18N
    btnSubstract2.setBorderPainted(false);
    btnSubstract2.setContentAreaFilled(false);
    jPanel3.add(btnSubstract2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, 50));

    btnSubstract3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/remove.png"))); // NOI18N
    btnSubstract3.setBorderPainted(false);
    btnSubstract3.setContentAreaFilled(false);
    jPanel3.add(btnSubstract3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, 50));

    btnAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/add(1).png"))); // NOI18N
    btnAdd3.setBorderPainted(false);
    btnAdd3.setContentAreaFilled(false);
    jPanel3.add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 40, 50));

    btnSubstract4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/remove.png"))); // NOI18N
    btnSubstract4.setBorderPainted(false);
    btnSubstract4.setContentAreaFilled(false);
    jPanel3.add(btnSubstract4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, 50));

    btnAdd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/add(1).png"))); // NOI18N
    btnAdd4.setBorderPainted(false);
    btnAdd4.setContentAreaFilled(false);
    jPanel3.add(btnAdd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 40, 50));

    btnSubstract5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/remove.png"))); // NOI18N
    btnSubstract5.setBorderPainted(false);
    btnSubstract5.setContentAreaFilled(false);
    jPanel3.add(btnSubstract5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, 50));

    btnAdd5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/add(1).png"))); // NOI18N
    btnAdd5.setBorderPainted(false);
    btnAdd5.setContentAreaFilled(false);
    jPanel3.add(btnAdd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 40, 50));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 370, 470));

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));

    btnNewVehicle.setBackground(new java.awt.Color(204, 204, 204));
    btnNewVehicle.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
    btnNewVehicle.setForeground(new java.awt.Color(0, 0, 0));
    btnNewVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jesus/assets/plus.png"))); // NOI18N
    btnNewVehicle.setText("                             Nuevo vehículo");
    btnNewVehicle.setBorderPainted(false);
    btnNewVehicle.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNewVehicleActionPerformed(evt);
      }
    });

    btnFinishCount.setBackground(new java.awt.Color(20, 175, 113));
    btnFinishCount.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
    btnFinishCount.setForeground(new java.awt.Color(255, 255, 255));
    btnFinishCount.setText("Finalizar Cuenta");
    btnFinishCount.setBorderPainted(false);
    btnFinishCount.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFinishCountActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        .addContainerGap(28, Short.MAX_VALUE)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnFinishCount, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnNewVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnNewVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnFinishCount, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 370, 90));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnNewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewVehicleActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnNewVehicleActionPerformed

  private void btnAddCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCountActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnAddCountActionPerformed

  private void btnFinishCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishCountActionPerformed
		this.setVisible(false);
    // TODO add your handling code here:
  }//GEN-LAST:event_btnFinishCountActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(UserAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(UserAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(UserAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(UserAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UserAppForm().setVisible(true);
			}
		});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnAdd2;
  private javax.swing.JButton btnAdd3;
  private javax.swing.JButton btnAdd4;
  private javax.swing.JButton btnAdd5;
  private javax.swing.JButton btnAddCount;
  private javax.swing.JButton btnCountedSection;
  private javax.swing.JButton btnCountingSection;
  private javax.swing.JButton btnFinishCount;
  private javax.swing.JButton btnMenu;
  private javax.swing.JButton btnNewVehicle;
  private javax.swing.JButton btnStatisticsSection;
  private javax.swing.JButton btnSubstract;
  private javax.swing.JButton btnSubstract2;
  private javax.swing.JButton btnSubstract3;
  private javax.swing.JButton btnSubstract4;
  private javax.swing.JButton btnSubstract5;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JLabel lblMovement;
  private javax.swing.JLabel lblVehicle;
  private javax.swing.JTextField txtQuantity;
  private javax.swing.JTextField txtQuantity2;
  private javax.swing.JTextField txtQuantity3;
  private javax.swing.JTextField txtQuantity4;
  private javax.swing.JTextField txtQuantity5;
  // End of variables declaration//GEN-END:variables
}
